---

- name: Check if "Swarm Mode" is enabled.
  shell: docker info
  changed_when: False
  register: docker_info

- block:

  - name: Init "Swarm Mode" on the first manager
    shell: docker swarm init --listen-addr {{ swarm_listen_address }} --advertise-addr {{ inventory_hostname }}
    when: "inventory_hostname == swarm_leader"

  - block:

    - name: Get the manager join-token
      shell: docker swarm join-token -q manager
      changed_when: False
      register: swarm_manager_token
      delegate_to: "{{ swarm_leader }}"
      delegate_facts: True

    - name: Join Swarm manager nodes
      shell: docker swarm join --listen-addr {{ swarm_listen_address }} --advertise-addr {{ inventory_hostname }} --token {{ swarm_manager_token.stdout }} {{ swarm_leader_address }}
      changed_when: False
      when: "docker_info.stdout.find('Swarm: pending') == -1"

    when: "'master' in group_names and inventory_hostname != swarm_leader"

  - block:

    - name: Get the worker join-token
      shell: docker swarm join-token -q worker
      changed_when: False
      register: swarm_worker_token
      delegate_to: "{{ swarm_leader }}"
      delegate_facts: True

    - name: Join Swarm worker nodes
      shell: docker swarm join --listen-addr {{ swarm_listen_address }} --advertise-addr {{ inventory_hostname }} --token {{ swarm_worker_token.stdout }} {{ swarm_leader_address }}
      changed_when: False
      when: "docker_info.stdout.find('Swarm: pending') == -1"

    when: "'worker' in group_names"

  when: "docker_info.stdout.find('Swarm: active') == -1"
